### ISSUE TITLE
Compiled at Win 11. Report back WARN

### ISSUE THREAD

**Issue by QustomQure** [6block/zkwork_ironminer#4]
cargo run --release  -- --pool 36.189.234.195:60006 --address "1e3c2ca8bba2e56e1a14b578f43abb08b6d28d8ac97a413a0c118efd2e39f1172d142568bc12f915414f16" --threads 28
warning: unused import: `futures::stream::StreamExt`
 --> src\main.rs:7:5
  |
7 | use futures::stream::StreamExt;
  |     ^^^^^^^^^^^^^^^^^^^^^^^^^^
  |
  = note: `#[warn(unused_imports)]` on by default

warning: unused import: `time::Duration`
 --> src\main.rs:9:22
  |
9 | use std::{sync::Arc, time::Duration};
  |                      ^^^^^^^^^^^^^^

warning: unused imports: `sync::oneshot`, `task`
  --> src\main.rs:10:22
   |
10 | use tokio::{runtime, sync::oneshot, task};
   |                      ^^^^^^^^^^^^^  ^^^^

warning: unused variable: `miner`
  --> src\main.rs:67:25
   |
67 | async fn handle_signals(miner: Arc<Miner>) -> Result<()> {
   |                         ^^^^^ help: if this is intentional, prefix it with an underscore: `_miner`
   |
   = note: `#[warn(unused_variables)]` on by default

warning: `zkwork_ironminer` (bin "zkwork_ironminer") generated 4 warnings
    Finished release [optimized] target(s) in 0.35s
     Running `target\release\zkwork_ironminer.exe --pool 36.189.234.195:60006 --address 1e3c2ca8bba2e56e1a14b578f43abb08b6d28d8ac97a413a0c118efd2e39f1172d142568bc12f915414f16 --threads 28`
 2022-09-10T17:08:07.354 INFO  zkwork_ironminer::stratum::stratum_client > Connecting to pool(36.189.234.195:60006)...
 2022-09-10T17:08:07.702 INFO  zkwork_ironminer::stratum::stratum_client > Connect pool success(36.189.234.195:60006)
 2022-09-10T17:08:17.376 INFO  zkwork_ironminer::miner                   > Found share: randomness(822954159) mining_request_id(13992) 96.73 MH/s .
 2022-09-10T17:08:19.410 INFO  zkwork_ironminer::miner                   > Found share: randomness(102481831) mining_request_id(13993) 94.34 MH/s .
 2022-09-10T17:08:19.629 INFO  zkwork_ironminer::miner                   > Found share: randomness(116993135) mining_request_id(13993) 94.34 MH/s .
 2022-09-10T17:08:28.777 INFO  zkwork_ironminer::miner                   > Found share: randomness(54127001) mining_request_id(13994) 94.02 MH/s .

![Screenshot (52)](https://user-images.githubusercontent.com/43998465/189487299-260bee2e-c96a-4c95-897c-416f2204741f.png)

Seems working fine. Maybe this WARN will help to improve something for you. Will be testing further

**Comment by hairtail** [comment]
> cargo run --release -- --pool 36.189.234.195:60006 --address "1e3c2ca8bba2e56e1a14b578f43abb08b6d28d8ac97a413a0c118efd2e39f1172d142568bc12f915414f16" --threads 28 warning: unused import: `futures::stream::StreamExt` --> src\main.rs:7:5 | 7 | use futures::stream::StreamExt; | ^^^^^^^^^^^^^^^^^^^^^^^^^^ | = note: `#[warn(unused_imports)]` on by default
> 
> warning: unused import: `time::Duration` --> src\main.rs:9:22 | 9 | use std::{sync::Arc, time::Duration}; | ^^^^^^^^^^^^^^
> 
> warning: unused imports: `sync::oneshot`, `task` --> src\main.rs:10:22 | 10 | use tokio::{runtime, sync::oneshot, task}; | ^^^^^^^^^^^^^ ^^^^
> 
> warning: unused variable: `miner` --> src\main.rs:67:25 | 67 | async fn handle_signals(miner: Arc) -> Result<()> { | ^^^^^ help: if this is intentional, prefix it with an underscore: `_miner` | = note: `#[warn(unused_variables)]` on by default
> 
> warning: `zkwork_ironminer` (bin "zkwork_ironminer") generated 4 warnings Finished release [optimized] target(s) in 0.35s Running `target\release\zkwork_ironminer.exe --pool 36.189.234.195:60006 --address 1e3c2ca8bba2e56e1a14b578f43abb08b6d28d8ac97a413a0c118efd2e39f1172d142568bc12f915414f16 --threads 28` 2022-09-10T17:08:07.354 INFO zkwork_ironminer::stratum::stratum_client > Connecting to pool(36.189.234.195:60006)... 2022-09-10T17:08:07.702 INFO zkwork_ironminer::stratum::stratum_client > Connect pool success(36.189.234.195:60006) 2022-09-10T17:08:17.376 INFO zkwork_ironminer::miner > Found share: randomness(822954159) mining_request_id(13992) 96.73 MH/s . 2022-09-10T17:08:19.410 INFO zkwork_ironminer::miner > Found share: randomness(102481831) mining_request_id(13993) 94.34 MH/s . 2022-09-10T17:08:19.629 INFO zkwork_ironminer::miner > Found share: randomness(116993135) mining_request_id(13993) 94.34 MH/s . 2022-09-10T17:08:28.777 INFO zkwork_ironminer::miner > Found share: randomness(54127001) mining_request_id(13994) 94.02 MH/s .
> 
> ![Screenshot (52)](https://user-images.githubusercontent.com/43998465/189487299-260bee2e-c96a-4c95-897c-416f2204741f.png)
> 
> Seems working fine. Maybe this WARN will help to improve something for you. Will be testing further

Thanks for your feedback. I have just disable some features that are not compatible in windows in 0.1.2. I will work on this later. We have something important to do now.
